### ISSUE TITLE
mimic sklearn api 

### ISSUE THREAD

**Issue by knaaptime** [pysal/region#15]
it would be good to provide a consistent api for all the clustering algos in Region so that the signatures are the same and mimic scikit-learn

currently, the `.fit` method aliases `.fit_from_scipy_sparse_matrix` but it might make more sense to instead alias `fit_from_w` which has a similar signature to scikit's [agglomerative w/ constraints](http://scikit-learn.org/stable/auto_examples/cluster/plot_agglomerative_clustering.html) 

there's also some inconsistency in the parameter names (e.g. `n_clusters` in SKATER, `n_regions` in maxp)

**Comment by ljwolf** [comment]
I think [skater uses the `W` object from pysal](https://github.com/pysal/region/blob/master/region/skater/skater.py#L52), and only forces it to be binary, and then only uses the sparse matrix. That'd be real simple to adjust directly in the api, using a `connectivity=` keyword argument. 

In my own research code, I've simply moved to using sparse matrices for input, rather than W objects, but idk how @sjsrey or other new maintainers feel about that.
